export const en = {
  dashboard: 'Dashboard',
  settings: 'Settings',
  about: 'About',
  connected: 'Connected',
  disconnected: 'Disconnected',
  connecting: 'Connecting...',
  total: 'Total',
  running: 'Running',
  stopped: 'Stopped',
  alerts: 'Alerts',
  searchPlaceholder: 'Search by name, ID or ports...',
  all: 'All',
  refresh: 'Refresh',
  connError: 'Connection Error',
  configureConn: 'Configure Connection',
  emptyContainers: 'No containers match the filter.',
  health: 'Health',
  ports: 'Ports',
  cpu: 'CPU',
  ram: 'RAM',
  status: 'Status',
  stop: 'Stop',
  start: 'Start',
  restart: 'Restart',
  metrics: 'Metrics',
  logs: 'Logs',
  console: 'Console',
  searchLogs: 'Search logs...',
  lines: 'Lines',
  refreshLogs: 'Refresh Logs',
  noLogs: 'No logs matching criteria.',
  loadingLogs: 'Loading logs...',
  run: 'Run',
  runCustomCmd: 'Run custom command',
  terminalOutput: 'Terminal output will show up here.',
  exitCode: 'Exit Code',
  // Settings
  serverSettings: 'Server Settings',
  serverDesc: 'Configure connection details for your DockerView-Go server.',
  hostAddress: 'Host Address',
  hostPlaceholder: 'e.g., http://192.168.1.100:8080',
  hostHint: 'For local emulators, use 10.0.2.2 (Android) or localhost (iOS/Web).',
  token: 'Security Token',
  tokenPlaceholder: 'Optional authorization token',
  tokenHint: 'Leave blank if the DockerView-Go server has authentication disabled.',
  save: 'Save Changes',
  testConn: 'Test Connection',
  connSuccess: 'Connection Succeeded',
  connFailed: 'Connection Failed',
  savedSuccess: 'Settings saved successfully!',
  language: 'Language Settings',
  langZh: 'Simplified Chinese',
  langEn: 'English',
  // About
  aboutSoftware: 'About Software',
  aboutDesc: 'DockerView is a premium universal monitoring client for DockerView-Go, supporting container monitoring, lifecycle management, and log filtering.',
  aboutAuthor: 'About Author',
  author: 'Developer',
  blog: 'Blog',
  sourceCode: 'Source Code',
  techStack: 'Tech Stack',
};

export type TranslationKey = keyof typeof en;
