import { TranslationKey } from './en';

export const zh: Record<TranslationKey, string> = {
  dashboard: '仪表盘',
  settings: '配置',
  about: '关于',
  connected: '已连接',
  disconnected: '未连接',
  connecting: '连接中...',
  total: '总容器',
  running: '运行中',
  stopped: '已停止',
  alerts: '警告项',
  searchPlaceholder: '搜索容器名称、ID 或端口...',
  all: '全部',
  refresh: '刷新',
  connError: '连接错误',
  configureConn: '配置连接',
  emptyContainers: '没有匹配的容器。',
  health: '健康度',
  ports: '端口',
  cpu: 'CPU',
  ram: '内存',
  status: '状态',
  stop: '停止',
  start: '启动',
  restart: '重启',
  metrics: '指标',
  logs: '日志',
  console: '控制台',
  searchLogs: '搜索日志...',
  lines: '行数',
  refreshLogs: '刷新日志',
  noLogs: '没有匹配的日志。',
  loadingLogs: '正在加载日志...',
  run: '执行',
  runCustomCmd: '执行自定义命令',
  terminalOutput: '终端输出将显示在这里。',
  exitCode: '退出状态码',
  // Settings
  serverSettings: '服务器配置',
  serverDesc: '配置 DockerView-Go 后端服务器的连接信息。',
  hostAddress: '主机地址',
  hostPlaceholder: '例如 http://192.168.1.100:8080',
  hostHint: '本地模拟器：Android 用 10.0.2.2，iOS/Web 用 localhost。',
  token: '安全 Token',
  tokenPlaceholder: '可选的身份验证 Token',
  tokenHint: '如果 DockerView-Go 服务启用了安全认证，请输入对应的 Token。',
  save: '保存修改',
  testConn: '测试连接',
  connSuccess: '连接成功',
  connFailed: '连接失败',
  savedSuccess: '配置保存成功！',
  language: '语言设置',
  langZh: '简体中文',
  langEn: 'English',
  // About
  aboutSoftware: '关于软件',
  aboutDesc: 'DockerView 是一款基于 Expo 和 React Native 构建的 Docker 容器监控与控制终端。作为 DockerView-Go 的客户端，它提供了实时的系统监控仪表盘、容器状态过滤、远程启动/停止/重启容器、日志过滤分析以及交互式命令执行等功能。',
  aboutAuthor: '关于作者',
  author: '开发作者',
  blog: '个人博客',
  sourceCode: '项目源码',
  techStack: '技术栈',
};
